[toolchain]
anchor_version = "0.28.0"
solana_version = "1.17.7"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_program = "6yUy54QMKPVx8iGVid1EoqCBGizzf7JRvKEseQb4usFu"

[programs.devnet]
staking_program = "6yUy54QMKPVx8iGVid1EoqCBGizzf7JRvKEseQb4usFu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
